/* SPDX-License-Identifier: GPL-3.0-or-later */
#include "../core/calculator.hpp"
#include <gtk/gtk.h>
#include <pango/pangocairo.h>
#include <cmath>
#include <iomanip>
#include <sstream>
#include <string>
namespace {
GtkWidget *expression_entry=nullptr,*result_label=nullptr,*status_label=nullptr;GtkCssProvider*css_provider=nullptr;double memory_value=0.0;
constexpr const char*kUiFont="MB Corpo S Title WEB";constexpr const char*kBrandFont="MB Corpo A Title Cond WEB";
std::string format_value(double v){std::ostringstream s;s<<std::setprecision(15)<<v;return s.str();}
bool font_family_available(const char*w){PangoFontMap*m=PANGO_FONT_MAP(pango_cairo_font_map_get_default());PangoFontFamily**f=nullptr;int n=0;pango_font_map_list_families(m,&f,&n);bool ok=false;for(int i=0;i<n;++i){const char*x=pango_font_family_get_name(f[i]);if(x&&g_ascii_strcasecmp(x,w)==0){ok=true;break;}}g_free(f);return ok;}
const char*ui_font(){return font_family_available(kUiFont)?kUiFont:"Sans";}const char*brand_font(){return font_family_available(kBrandFont)?kBrandFont:ui_font();}
void status(const char*t,bool fault=false){gtk_label_set_text(GTK_LABEL(status_label),t);if(fault)gtk_widget_add_css_class(status_label,"fault");else gtk_widget_remove_css_class(status_label,"fault");}
bool current_value(double&v){const char*t=gtk_editable_get_text(GTK_EDITABLE(expression_entry));auto r=infiltrator::calc::evaluate(t?t:"");if(!r.ok){gtk_label_set_text(GTK_LABEL(result_label),("Error: "+r.error).c_str());status("CALCULATION ERROR",true);return false;}v=r.value;return true;}
void set_expression(const std::string&s){gtk_editable_set_text(GTK_EDITABLE(expression_entry),s.c_str());gtk_editable_set_position(GTK_EDITABLE(expression_entry),-1);gtk_widget_grab_focus(expression_entry);}
void calculate(){double v;if(!current_value(v))return;gtk_label_set_text(GTK_LABEL(result_label),format_value(v).c_str());status("READY");}
void clear_calculation(){set_expression("");gtk_label_set_text(GTK_LABEL(result_label),"0");status("READY");}
void insert_text(const char*t){int p=gtk_editable_get_position(GTK_EDITABLE(expression_entry));gtk_editable_insert_text(GTK_EDITABLE(expression_entry),t,-1,&p);gtk_editable_set_position(GTK_EDITABLE(expression_entry),p);gtk_widget_grab_focus(expression_entry);}
void backspace(){int p=gtk_editable_get_position(GTK_EDITABLE(expression_entry));if(p>0)gtk_editable_delete_text(GTK_EDITABLE(expression_entry),p-1,p);gtk_widget_grab_focus(expression_entry);}
void unary_transform(const char*op){double v;if(!current_value(v))return;if(g_strcmp0(op,"±")==0)v=-v;else if(g_strcmp0(op,"x²")==0)v*=v;else if(g_strcmp0(op,"√")==0){if(v<0){status("DOMAIN ERROR",true);return;}v=std::sqrt(v);}else if(g_strcmp0(op,"1/x")==0){if(v==0){status("DIVISION BY ZERO",true);return;}v=1.0/v;}set_expression(format_value(v));gtk_label_set_text(GTK_LABEL(result_label),format_value(v).c_str());status("READY");}
void on_activate(GtkEntry*){calculate();}
void on_button_clicked(GtkButton*b,gpointer){const char*l=gtk_button_get_label(b);if(!l)return;if(!g_strcmp0(l,"=")){calculate();return;}if(!g_strcmp0(l,"C")){clear_calculation();return;}if(!g_strcmp0(l,"⌫")){backspace();return;}if(!g_strcmp0(l,"±")||!g_strcmp0(l,"x²")||!g_strcmp0(l,"√")||!g_strcmp0(l,"1/x")){unary_transform(l);return;}if(!g_strcmp0(l,"MC")){memory_value=0;status("MEMORY CLEARED");return;}if(!g_strcmp0(l,"MR")){insert_text(format_value(memory_value).c_str());status("MEMORY RECALL");return;}if(!g_strcmp0(l,"M+")||!g_strcmp0(l,"M-")){double v;if(current_value(v)){memory_value+=(!g_strcmp0(l,"M+"))?v:-v;status("MEMORY UPDATED");}return;}insert_text(l);}
GtkWidget*button(const char*t,const char*c=nullptr){GtkWidget*b=gtk_button_new_with_label(t);gtk_widget_add_css_class(b,"calc-button");if(c)gtk_widget_add_css_class(b,c);g_signal_connect(b,"clicked",G_CALLBACK(on_button_clicked),nullptr);gtk_widget_set_hexpand(b,TRUE);gtk_widget_set_vexpand(b,TRUE);return b;}
void apply_css(GtkWidget*w){std::string u=ui_font(),b=brand_font();std::string css="*{font-family:\""+u+"\";font-weight:400}window,.shell{background:#050608;color:#E8ECEF}.shell{padding:20px}.brand-title{font-family:\""+b+"\";font-size:26px;color:#EEF1F3}.mode,.status{font-size:10px;font-weight:700;letter-spacing:.10em;color:#899198}.display{background:#101318;border:1px solid #353A40;border-radius:12px;padding:14px}.expression{background:#0E1115;color:#AEB6BD;border:1px solid #353A40;border-radius:8px;padding:9px 11px;min-height:22px}.result{font-family:\""+b+"\";font-size:36px;color:#EEF1F3;padding-top:8px}.status.fault{color:#C96B6B}.calc-button{background:#171B20;color:#E8ECEF;border:1px solid #353A40;border-radius:10px;min-height:44px;font-size:15px}.calc-button:hover{background:#22272D;border-color:#6A737C}.calc-button:active{background:#2B3137}.operation{background:#20252B;color:#D7DDE2;font-weight:700}.clear{color:#D19E47;font-weight:700}.equals{background:#D7DDE2;color:#111418;font-weight:700}.equals:hover{background:#EEF1F3}.memory{color:#BEC7CF;font-weight:700}.footer{color:#899198;font-size:10px}";css_provider=gtk_css_provider_new();gtk_css_provider_load_from_data(css_provider,css.c_str(),-1);gtk_style_context_add_provider_for_display(gtk_widget_get_display(w),GTK_STYLE_PROVIDER(css_provider),GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);}
void activate(GtkApplication*a,gpointer){GtkWidget*w=gtk_application_window_new(a);gtk_window_set_title(GTK_WINDOW(w),"Infiltrator Calc");gtk_window_set_default_size(GTK_WINDOW(w),420,690);GtkWidget*shell=gtk_box_new(GTK_ORIENTATION_VERTICAL,12);gtk_widget_add_css_class(shell,"shell");gtk_window_set_child(GTK_WINDOW(w),shell);apply_css(w);GtkWidget*h=gtk_box_new(GTK_ORIENTATION_HORIZONTAL,10);gtk_box_append(GTK_BOX(shell),h);GtkWidget*t=gtk_label_new("Infiltrator Calc");gtk_widget_add_css_class(t,"brand-title");gtk_box_append(GTK_BOX(h),t);GtkWidget*sp=gtk_box_new(GTK_ORIENTATION_HORIZONTAL,0);gtk_widget_set_hexpand(sp,TRUE);gtk_box_append(GTK_BOX(h),sp);GtkWidget*m=gtk_label_new("STANDARD");gtk_widget_add_css_class(m,"mode");gtk_box_append(GTK_BOX(h),m);GtkWidget*d=gtk_box_new(GTK_ORIENTATION_VERTICAL,7);gtk_widget_add_css_class(d,"display");gtk_box_append(GTK_BOX(shell),d);expression_entry=gtk_entry_new();gtk_entry_set_placeholder_text(GTK_ENTRY(expression_entry),"Enter expression");gtk_widget_add_css_class(expression_entry,"expression");gtk_entry_set_alignment(GTK_ENTRY(expression_entry),1);g_signal_connect(expression_entry,"activate",G_CALLBACK(on_activate),nullptr);gtk_box_append(GTK_BOX(d),expression_entry);result_label=gtk_label_new("0");gtk_widget_add_css_class(result_label,"result");gtk_widget_set_halign(result_label,GTK_ALIGN_END);gtk_label_set_ellipsize(GTK_LABEL(result_label),PANGO_ELLIPSIZE_START);gtk_box_append(GTK_BOX(d),result_label);status_label=gtk_label_new("READY");gtk_widget_add_css_class(status_label,"status");gtk_widget_set_halign(status_label,GTK_ALIGN_END);gtk_box_append(GTK_BOX(d),status_label);
GtkWidget*g=gtk_grid_new();gtk_grid_set_row_spacing(GTK_GRID(g),6);gtk_grid_set_column_spacing(GTK_GRID(g),6);gtk_widget_set_vexpand(g,TRUE);gtk_box_append(GTK_BOX(shell),g);struct K{const char*l;const char*c;};const K keys[][4]={{{"MC","memory"},{"MR","memory"},{"M+","memory"},{"M-","memory"}},{{"C","clear"},{"⌫","clear"},{"%","operation"},{"/","operation"}},{{"1/x","operation"},{"x²","operation"},{"√","operation"},{"^","operation"}},{{"7",nullptr},{"8",nullptr},{"9",nullptr},{"*","operation"}},{{"4",nullptr},{"5",nullptr},{"6",nullptr},{"-","operation"}},{{"1",nullptr},{"2",nullptr},{"3",nullptr},{"+","operation"}},{{"±","operation"},{"0",nullptr},{".",nullptr},{"=","equals"}},{{"(","operation"},{")","operation"},{"%","operation"},{"=","equals"}}};for(guint r=0;r<8;++r)for(guint c=0;c<4;++c)gtk_grid_attach(GTK_GRID(g),button(keys[r][c].l,keys[r][c].c),c,r,1,1);GtkWidget*f=gtk_label_new("Standard calculator  ·  Memory  ·  Keyboard ready");gtk_widget_add_css_class(f,"footer");gtk_widget_set_halign(f,GTK_ALIGN_START);gtk_box_append(GTK_BOX(shell),f);gtk_window_present(GTK_WINDOW(w));gtk_widget_grab_focus(expression_entry);}
}
int main(int argc,char**argv){GtkApplication*a=gtk_application_new("net.ssmith.infiltrator.calc",G_APPLICATION_DEFAULT_FLAGS);g_signal_connect(a,"activate",G_CALLBACK(activate),nullptr);int s=g_application_run(G_APPLICATION(a),argc,argv);if(css_provider)g_object_unref(css_provider);g_object_unref(a);return s;}
